#!/bin/bash

cd $(dirname $(readlink -f $0))

if ! [ -f .env ]
then
    echo "no .env file found, exiting"
    exit 1
fi

if ! [ -f *compose.yaml ]
then
    echo "no docker compose file found, exiting"
    exit 1
fi

. .env

if [ -z "$COMPOSE_PROJECT_NAME" ]
then
    COMPOSE_PROJECT_NAME=$(basename $PWD)
    echo "using dirname as project: $COMPOSE_PROJECT_NAME"
    echo "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME" >>.env
fi

case $(basename $0) in
    (start)
        docker compose -p $COMPOSE_PROJECT_NAME up -d --remove-orphans
    ;;
    (stopp)
        docker compose -p $COMPOSE_PROJECT_NAME down
    ;;
    (*)
        echo "illegal name for script used, please use start and stopp"
        exit 1
    ;;
esac
